// setup/windicss.ts

import { defineWindiSetup } from "@slidev/types";

// extending the builtin windicss configurations
export default defineWindiSetup(() => ({
  shortcuts: {
    // custom the default background
    "bg-main": "bg-white text-[#181818] dark:bg-[#121212] dark:text-[#ddd]",
  },
  theme: {
    extend: {
      colors: {
        "light-primary": "#9c4044",
        "light-on-primary": "#ffffff",
        "light-primary-container": "#ffd9d9",
        "light-on-primary-container": "#400007",
        "light-secondary": "#775656",
        "light-on-secondary": "#ffffff",
        "light-secondary-container": "#ffdad9",
        "light-on-secondary-container": "#2c1515",
        "light-tertiary": "#755a2f",
        "light-on-tertiary": "#ffffff",
        "light-tertiary-container": "#ffddaa",
        "light-on-tertiary-container": "#281800",
        "light-error": "#ba1b1b",
        "light-error-container": "#ffdad4",
        "light-on-error": "#ffffff",
        "light-on-error-container": "#410001",
        "light-background": "#fcfcfc",
        "light-on-background": "#211a1a",
        "light-surface": "#fcfcfc",
        "light-on-surface": "#211a1a",
        "light-surface-variant": "#f4dddc",
        "light-on-surface-variant": "#534343",
        "light-outline": "#857372",
        "light-inverse-on-surface": "#fbeeed",
        "light-inverse-surface": "#362f2f",
        "light-inverse-primary": "#ffb3b3",
        "light-shadow": "#000000",
        "dark-primary": "#ffb3b3",
        "dark-on-primary": "#5f131a",
        "dark-primary-container": "#7e2a2f",
        "dark-on-primary-container": "#ffd9d9",
        "dark-secondary": "#e7bdbc",
        "dark-on-secondary": "#442929",
        "dark-secondary-container": "#5d3f3f",
        "dark-on-secondary-container": "#ffdad9",
        "dark-tertiary": "#e4c18d",
        "dark-on-tertiary": "#422c05",
        "dark-tertiary-container": "#5b431a",
        "dark-on-tertiary-container": "#ffddaa",
        "dark-error": "#ffb4a9",
        "dark-error-container": "#930006",
        "dark-on-error": "#680003",
        "dark-on-error-container": "#ffdad4",
        "dark-background": "#211a1a",
        "dark-on-background": "#ede0df",
        "dark-surface": "#211a1a",
        "dark-on-surface": "#ede0df",
        "dark-surface-variant": "#534343",
        "dark-on-surface-variant": "#d8c2c1",
        "dark-outline": "#9f8c8b",
        "dark-inverse-on-surface": "#211a1a",
        "dark-inverse-surface": "#ede0df",
        "dark-inverse-primary": "#9c4044",
        "dark-shadow": "#000000",
      },
    },
  },
}));
